### ISSUE TITLE
help setting ms4alg on mountainlab 

### ISSUE THREAD

**Issue by ferchaure** [magland/ml_ms4alg#33]
Hi, I have been trying mountainlab (I installed on ubuntu 18.04 using the conda commands), I used ephys process without issues but when I try to run ms4alg.sort I got errors for hours (maybe a loop of errors?)

Before that I got an error related to missing modules in dask and I run:
`pip install dask[complete]
`
After that I try again and got:
(I show just the first error)

(mountainlab) fer@iibm:~/data/msort_test$ ml-run-process ms4alg.sort --inputs timeseries:./OUTPUT/whit.mda --outputs firings_out:./OUTPUT/firings.mda --parameters detect_sign:-1 adjacency_radius:0 detect_threshold:7
[ Getting processor spec... ]
[ Checking inputs and substituting prvs ... ]
[ Computing process signature ... ]
Process signature: 7b883d9943c4e480696a2a41266f9ef5b92b9954
[ Checking outputs... ]
{"firings_out":"./OUTPUT/firings.mda"}
Processing ouput - ./OUTPUT/firings.mda
false
{"firings_out":"/home/fer/data/msort_test/OUTPUT/firings.mda"}
[ Checking process cache ... ]
[ Creating temporary directory ... ]
[ Creating links to input files... ]
[ Preparing temporary outputs... ]
Processing ouput - /home/fer/data/msort_test/OUTPUT/firings.mda
false
[ Initializing process ... ]
[ Running ... ] /home/fer/anaconda3/envs/mountainlab/bin/python3 /home/fer/anaconda3/envs/mountainlab/lib/node_modules/mountainlab/system-packages/ml_ms4alg/ms4alg_spec.py.mp ms4alg.sort --_tempdir=/tmp/mountainlab-tmp/tempdir_7b883d9943_5YWCx8 --timeseries=/tmp/mountainlab-tmp/tempdi$_7b883d9943_5YWCx8/input_timeseries_RMRQM9Xn.mda --geom= --firings_out=/tmp/mountainlab-tmp/tempdir_7b883d9943_5YWCx8/output_firings_out.mda --detect_sign=-1 --adjacency_radius=0 --detect_threshold=7
Using tempdir=/tmp/mountainlab-tmp/tempdir_7b883d9943_5YWCx8
Num. workers = 8
Preparing /tmp/mountainlab-tmp/tempdir_7b883d9943_5YWCx8/timeseries.hdf5...
Preparing neighborhood sorters (M=24, N=45967722)...

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fer/anaconda3/envs/mountainlab/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/fer/anaconda3/envs/mountainlab/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/home/fer/anaconda3/envs/mountainlab/lib/python3.6/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/fer/anaconda3/envs/mountainlab/lib/python3.6/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/home/fer/anaconda3/envs/mountainlab/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/fer/anaconda3/envs/mountainlab/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/fer/anaconda3/envs/mountainlab/lib/python3.6/runpy.py", line 85, in _run_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/fer/anaconda3/envs/mountainlab/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fer/anaconda3/envs/mountainlab/lib/node_modules/mountainlab/system-packages/ml_ms4alg/ms4alg_spec.py.mp", line 13, in <module>
    if not PM.run(sys.argv):
  File "/home/fer/anaconda3/envs/mountainlab/lib/python3.6/site-packages/mountainlab_pytools/processormanager/processormanager_impl.py", line 37, in run
    return P(**args)
  File "/home/fer/anaconda3/envs/mountainlab/lib/python3.6/site-packages/ml_ms4alg/p_ms4alg.py", line 79, in **sort**
    MS4.sort()
  File "/home/fer/anaconda3/envs/mountainlab/lib/python3.6/site-packages/ml_ms4alg/ms4alg.py", line 664, in sort
    os.remove(temp_hdf5_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/mountainlab-tmp/tempdir_7b883d9943_5YWCx8/timeseries.hdf5'

**Comment by ferchaure** [comment]
Following your readme [here](https://github.com/flatironinstitute/mountainsort_examples/blob/master/README.md)

and installing all the packages:
`
conda install -c flatiron -c conda-forge 	mountainlab mountainlab_pytools ml_ephys ml_ms3 ml_ms4alg 	ml_pyms
`
It works!

**Comment by ferchaure** [comment]
Hi again, that fix installs the old version of mountainsort on conda. If I install the latest ms4alg using pip I still got that error, any idea?
